export const categories = {
  data: [
    {
      slug: "beauty",
      name: "Beauty",
      url: "/category/beauty",
      imageUrl: "/assets/images/category/makeup.png",
    },
    {
      slug: "fragrances",
      name: "Fragrances",
      url: "/category/fragrances",
      imageUrl: "/assets/images/category/fragrance2.png",
    },
    {
      slug: "furniture",
      name: "Furniture",
      url: "/category/furniture",
      imageUrl: "/assets/images/category/furniture2.png",
    },
    {
      slug: "groceries",
      name: "Groceries",
      url: "/category/groceries",
      imageUrl: "/assets/images/category/grocery.png",
    },
    {
      slug: "home-decoration",
      name: "Home Decoration",
      url: "/category/home-decoration",
      imageUrl: "/assets/images/category/home-decoration.png",
    },
    {
      slug: "kitchen-accessories",
      name: "Kitchen Accessories",
      url: "/category/kitchen-accessories",
      imageUrl: "/assets/images/category/kitchen-accessories.png",
    },
    {
      slug: "laptops",
      name: "Laptops",
      url: "/category/laptops",
      imageUrl: "/assets/images/category/laptop.png",
    },
    {
      slug: "mens-shirts",
      name: "Mens Shirts",
      url: "/category/mens-shirts",
      imageUrl: "/assets/images/category/shirts.png",
    },
    {
      slug: "mens-shoes",
      name: "Mens Shoes",
      url: "/category/mens-shoes",
      imageUrl: "/assets/images/category/shoes.png",
    },
    {
      slug: "mens-watches",
      name: "Mens Watches",
      url: "/category/mens-watches",
      imageUrl: "/assets/images/category/watches.png",
    },
    {
      slug: "mobile-accessories",
      name: "Mobile Accessories",
      url: "/category/mobile-accessories",
      imageUrl: "/assets/images/category/mobile-accessories.png",
    },
    {
      slug: "motorcycle",
      name: "Motorcycle",
      url: "/category/motorcycle",
      imageUrl: "/assets/images/category/motorcycle.png",
    },
    {
      slug: "skin-care",
      name: "Skin Care",
      url: "/category/skin-care",
      imageUrl: "/assets/images/category/skincare.png",
    },
    {
      slug: "smartphones",
      name: "Smartphones",
      url: "/category/smartphones",
      imageUrl: "/assets/images/category/smartphones.png",
    },
    {
      slug: "sports-accessories",
      name: "Sports Accessories",
      url: "/category/sports-accessories",
      imageUrl: "/assets/images/category/sports-accessories.png",
    },
    {
      slug: "sunglasses",
      name: "Sunglasses",
      url: "/category/sunglasses",
      imageUrl: "/assets/images/category/sunglasses.png",
    },
    {
      slug: "tablets",
      name: "Tablets",
      url: "/category/tablets",
      imageUrl: "/assets/images/category/tablets.png",
    },
    {
      slug: "tops",
      name: "Tops",
      url: "/category/tops",
      imageUrl: "/assets/images/category/tops.png",
    },
    {
      slug: "vehicle",
      name: "Vehicle",
      url: "/category/vehicle",
      imageUrl: "/assets/images/category/vehicles.png",
    },
    {
      slug: "womens-bags",
      name: "Womens Bags",
      url: "/category/womens-bags",
      imageUrl: "/assets/images/category/women-bags.png",
    },
    {
      slug: "womens-dresses",
      name: "Womens Dresses",
      url: "/category/womens-dresses",
      imageUrl: "/assets/images/category/women-dresses.png",
    },
    {
      slug: "womens-jewellery",
      name: "Womens Jewellery",
      url: "/category/womens-jewellery",
      imageUrl: "/assets/images/category/women-jewellery.png",
    },
    {
      slug: "womens-shoes",
      name: "Womens Shoes",
      url: "/category/womens-shoes",
      imageUrl: "/assets/images/category/women-shoes.png",
    },
    {
      slug: "womens-watches",
      name: "Womens Watches",
      url: "/category/womens-watches",
      imageUrl: "/assets/images/category/women-watches.png",
    },
  ],
  viewLimit: 10,
};

export const socialLinks = [
  {
    name: "Facebook",
    url: "",
  },
  {
    name: "Instagram",
    url: "",
  },
  {
    name: "Twitter",
    url: "",
  },
];

export const footerLinks = [
  {
    name: "Home",
    url: "/",
  },
  {
    name: "About Us",
    url: "/aboutus",
  },
  {
    name: "Contact Us",
    url: "/contactus",
  },
  {
    name: "Help & Support",
    url: "/help-support",
  },
  {
    name: "Privacy Policy",
    url: "/privacy-policy",
  },
];

export const CURRENCY_LABEL = {
  USD: { name: "United States Dollar", symbol: "$" },
  AED: { name: "United Arab Emirates Dirham", symbol: "د.إ" },
  AFN: { name: "Afghan Afghani", symbol: "؋" },
  ALL: { name: "Albanian Lek", symbol: null },
  AMD: { name: "Armenian Dram", symbol: "֏" },
  ANG: { name: "Netherlands Antillean Guilder", symbol: "ƒ" },
  AOA: { name: "Angolan Kwanza", symbol: null },
  ARS: { name: "Argentine Peso", symbol: "$" },
  AUD: { name: "Australian Dollar", symbol: "$" },
  AWG: { name: "Aruban Florin", symbol: "ƒ" },
  AZN: { name: "Azerbaijani Manat", symbol: "₼" },
  BAM: { name: "Bosnia-Herzegovina Convertible Mark", symbol: null },
  BBD: { name: "Barbadian Dollar", symbol: "$" },
  BDT: { name: "Bangladeshi Taka", symbol: "৳" },
  BGN: { name: "Bulgarian Lev", symbol: null },
  BHD: { name: "Bahraini Dinar", symbol: null },
  BIF: { name: "Burundian Franc", symbol: null },
  BMD: { name: "Bermudian Dollar", symbol: "$" },
  BND: { name: "Brunei Dollar", symbol: "$" },
  BOB: { name: "Bolivian Boliviano", symbol: "Bs." },
  BRL: { name: "Brazilian Real", symbol: "R$" },
  BSD: { name: "Bahamian Dollar", symbol: "$" },
  BTN: { name: "Bhutanese Ngultrum", symbol: null },
  BWP: { name: "Botswana Pula", symbol: null },
  BYN: { name: "Belarusian Ruble", symbol: null },
  BZD: { name: "Belize Dollar", symbol: "$" },
  CAD: { name: "Canadian Dollar", symbol: "$" },
  CDF: { name: "Congolese Franc", symbol: null },
  CHF: { name: "Swiss Franc", symbol: null },
  CLP: { name: "Chilean Peso", symbol: "$" },
  CNY: { name: "Chinese Yuan", symbol: "¥" },
  COP: { name: "Colombian Peso", symbol: "$" },
  CRC: { name: "Costa Rican Colón", symbol: "₡" },
  CUP: { name: "Cuban Peso", symbol: "$" },
  CVE: { name: "Cape Verdean Escudo", symbol: null },
  CZK: { name: "Czech Koruna", symbol: null },
  DJF: { name: "Djiboutian Franc", symbol: null },
  DKK: { name: "Danish Krone", symbol: null },
  DOP: { name: "Dominican Peso", symbol: "RD$" },
  DZD: { name: "Algerian Dinar", symbol: null },
  EGP: { name: "Egyptian Pound", symbol: "£" },
  ERN: { name: "Eritrean Nakfa", symbol: null },
  ETB: { name: "Ethiopian Birr", symbol: null },
  EUR: { name: "Euro", symbol: "€" },
  FJD: { name: "Fijian Dollar", symbol: "$" },
  FKP: { name: "Falkland Islands Pound", symbol: "£" },
  FOK: { name: "Faroese Króna", symbol: null },
  GBP: { name: "British Pound Sterling", symbol: "£" },
  GEL: { name: "Georgian Lari", symbol: null },
  GGP: { name: "Guernsey Pound", symbol: "£" },
  GHS: { name: "Ghanaian Cedi", symbol: "₵" },
  GIP: { name: "Gibraltar Pound", symbol: "£" },
  GMD: { name: "Gambian Dalasi", symbol: null },
  GNF: { name: "Guinean Franc", symbol: null },
  GTQ: { name: "Guatemalan Quetzal", symbol: "Q" },
  GYD: { name: "Guyanese Dollar", symbol: "$" },
  HKD: { name: "Hong Kong Dollar", symbol: "$" },
  HNL: { name: "Honduran Lempira", symbol: "L" },
  HRK: { name: "Croatian Kuna", symbol: null },
  HTG: { name: "Haitian Gourde", symbol: null },
  HUF: { name: "Hungarian Forint", symbol: null },
  IDR: { name: "Indonesian Rupiah", symbol: "Rp" },
  ILS: { name: "Israeli New Shekel", symbol: "₪" },
  IMP: { name: "Isle of Man Pound", symbol: "£" },
  INR: { name: "Indian Rupee", symbol: "₹" },
  IQD: { name: "Iraqi Dinar", symbol: null },
  IRR: { name: "Iranian Rial", symbol: "﷼" },
  ISK: { name: "Icelandic Króna", symbol: null },
  JEP: { name: "Jersey Pound", symbol: "£" },
  JMD: { name: "Jamaican Dollar", symbol: "$" },
  JOD: { name: "Jordanian Dinar", symbol: null },
  JPY: { name: "Japanese Yen", symbol: "¥" },
  KES: { name: "Kenyan Shilling", symbol: null },
  KGS: { name: "Kyrgyzstani Som", symbol: null },
  KHR: { name: "Cambodian Riel", symbol: "៛" },
  KID: { name: "Kiribati Dollar", symbol: null },
  KMF: { name: "Comorian Franc", symbol: null },
  KRW: { name: "South Korean Won", symbol: "₩" },
  KWD: { name: "Kuwaiti Dinar", symbol: null },
  KYD: { name: "Cayman Islands Dollar", symbol: "$" },
  KZT: { name: "Kazakhstani Tenge", symbol: "₸" },
  LAK: { name: "Lao Kip", symbol: "₭" },
  LBP: { name: "Lebanese Pound", symbol: "ل.ل" },
  LKR: { name: "Sri Lankan Rupee", symbol: null },
  LRD: { name: "Liberian Dollar", symbol: "$" },
  LSL: { name: "Lesotho Loti", symbol: null },
  LYD: { name: "Libyan Dinar", symbol: null },
  MAD: { name: "Moroccan Dirham", symbol: null },
  MDL: { name: "Moldovan Leu", symbol: null },
  MGA: { name: "Malagasy Ariary", symbol: null },
  MKD: { name: "Macedonian Denar", symbol: null },
  MMK: { name: "Myanmar Kyat", symbol: null },
  MNT: { name: "Mongolian Tögrög", symbol: "₮" },
  MOP: { name: "Macanese Pataca", symbol: null },
  MRU: { name: "Mauritanian Ouguiya", symbol: null },
  MUR: { name: "Mauritian Rupee", symbol: null },
  MVR: { name: "Maldivian Rufiyaa", symbol: null },
  MWK: { name: "Malawian Kwacha", symbol: null },
  MXN: { name: "Mexican Peso", symbol: "$" },
  MYR: { name: "Malaysian Ringgit", symbol: null },
  MZN: { name: "Mozambican Metical", symbol: null },
  NAD: { name: "Namibian Dollar", symbol: "$" },
  NGN: { name: "Nigerian Naira", symbol: "₦" },
  NIO: { name: "Nicaraguan Córdoba", symbol: "C$" },
  NOK: { name: "Norwegian Krone", symbol: null },
  NPR: { name: "Nepalese Rupee", symbol: null },
  NZD: { name: "New Zealand Dollar", symbol: "$" },
  OMR: { name: "Omani Rial", symbol: null },
  PAB: { name: "Panamanian Balboa", symbol: null },
  PEN: { name: "Peruvian Sol", symbol: "S/." },
  PGK: { name: "Papua New Guinean Kina", symbol: null },
  PHP: { name: "Philippine Peso", symbol: "₱" },
  PKR: { name: "Pakistani Rupee", symbol: "₨" },
  PLN: { name: "Polish Złoty", symbol: "zł" },
  PYG: { name: "Paraguayan Guaraní", symbol: "₲" },
  QAR: { name: "Qatari Riyal", symbol: "ر.ق" },
  RON: { name: "Romanian Leu", symbol: null },
  RSD: { name: "Serbian Dinar", symbol: null },
  RUB: { name: "Russian Ruble", symbol: "₽" },
  RWF: { name: "Rwandan Franc", symbol: null },
  SAR: { name: "Saudi Riyal", symbol: "ر.س" },
  SBD: { name: "Solomon Islands Dollar", symbol: "$" },
  SCR: { name: "Seychellois Rupee", symbol: null },
  SDG: { name: "Sudanese Pound", symbol: null },
  SEK: { name: "Swedish Krona", symbol: null },
  SGD: { name: "Singapore Dollar", symbol: "$" },
  SHP: { name: "Saint Helena Pound", symbol: "£" },
  SLE: { name: "Sierra Leonean Leone", symbol: null },
  SLL: { name: "Sierra Leonean Leone", symbol: null },
  SOS: { name: "Somali Shilling", symbol: null },
  SRD: { name: "Surinamese Dollar", symbol: "$" },
  SSP: { name: "South Sudanese Pound", symbol: null },
  STN: { name: "São Tomé and Príncipe Dobra", symbol: null },
  SYP: { name: "Syrian Pound", symbol: "£" },
  SZL: { name: "Eswatini Lilangeni", symbol: null },
  THB: { name: "Thai Baht", symbol: "฿" },
  TJS: { name: "Tajikistani Somoni", symbol: null },
  TMT: { name: "Turkmenistani Manat", symbol: null },
  TND: { name: "Tunisian Dinar", symbol: null },
  TOP: { name: "Tongan Paʻanga", symbol: null },
  TRY: { name: "Turkish Lira", symbol: "₺" },
  TTD: { name: "Trinidad and Tobago Dollar", symbol: "$" },
  TVD: { name: "Tuvaluan Dollar", symbol: null },
  TWD: { name: "New Taiwan Dollar", symbol: "NT$" },
  TZS: { name: "Tanzanian Shilling", symbol: null },
  UAH: { name: "Ukrainian Hryvnia", symbol: "₴" },
  UGX: { name: "Ugandan Shilling", symbol: null },
  UYU: { name: "Uruguayan Peso", symbol: "$U" },
  UZS: { name: "Uzbekistani Soʻm", symbol: null },
  VES: { name: "Venezuelan Bolívar Soberano", symbol: null },
  VND: { name: "Vietnamese Đồng", symbol: "₫" },
  VUV: { name: "Vanuatu Vatu", symbol: null },
  WST: { name: "Samoan Tālā", symbol: null },
  XAF: { name: "Central African CFA Franc", symbol: null },
  XCD: { name: "East Caribbean Dollar", symbol: null },
  XDR: { name: "Special Drawing Rights", symbol: null },
  XOF: { name: "West African CFA Franc", symbol: null },
  XPF: { name: "CFP Franc", symbol: null },
  YER: { name: "Yemeni Rial", symbol: null },
  ZAR: { name: "South African Rand", symbol: null },
  ZMW: { name: "Zambian Kwacha", symbol: null },
  ZWL: { name: "Zimbabwean Dollar", symbol: null },
};
